### PR TITLE
BVC-71 :: TOUTOC bug in new-key-claim endpoint

### LINKED ISSUE #147: BVC-71 :: TOUTOC bug in new-key-claim endpoint
Similar problem to #140 but on new-key-claim path.

"
A solution to this vulnerability would be to check and add the one-time-code entry in a single SQL command. If the intented functionality of this endpoint is to ensure unique hash per one-time-code, developers may consider using the the sql REPLACE command for hashID requests."

Alternatively, it would probably make sense to have a unique constraint on the hashID field as well, which, would fix this, and any other potential bug we may have lurking.

### PR DESCRIPTION
**Pull request by maxneuvians**
Closes #147. 

This PR changes the HashID logic by incorporating all the required queries into a single transaction with a "FOR UPDATE" lock. This removes the race condition where by two one time codes could have the same HashIDs.

### CODE REVIEW

File: pkg/persistence/db.go [hunk 1]
```diff
@@ -142,6 +141,10 @@ func (c *conn) ClaimKey(oneTimeCode string, appPublicKey []byte) ([]byte, error)
 	return claimKey(c.db, oneTimeCode, appPublicKey)
 }
 
+// ErrHashIDClaimed is returned when the client tries to get a new code for a 
+// HashID that has laready used the code
```
Comment (obrien-j) [inline pkg/persistence/db.go:145]: Minor typo

Comment (maxneuvians) [reply pkg/persistence/db.go]: Fixed
